title: "2021 IEEE SA Standards Style Manual"
subtitle: ""
version: ""
creator: "IEEE" # E.g. the author
contributor: "" # E.g. other contributors
subject: "" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "The IEEE Standards Style Manual (PDF) establishes preferred style for the preparation and structure of proposed IEEE standards (drafts). It also cites requirements of the *IEEE SA Standards Board Operations Manual* that are related to the development and publication of IEEE standards." # E.g. the blurb
publisher: "IEEE" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2021-04-29" # YYYY-MM-DD e.g. publication date
modified: "2021-04-29" # YYYY-MM-DD e.g. date of last revision
type: "Standard" # e.g. Standard, User Guide, Whitepaper
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "IEEE" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "cover.jpg"
status: "Final" # status, e.g., Draft, Final, Review

products: # Metadata for each product for this title (only use values that override parent metadata)
  screen-pdf:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-cover"
      - "0-1-introduction"
      - "0-2-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "annex-a"
